version: "3.4"

services:
  mongo_database:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  redis_database:
    image: redis
    restart: always
    ports:
      - 6379:6379

  propsycho_server:
    image: propsycho_server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      REDIS_HOST: redis_database
      MONGOOSE_HOST: mongo_database
      BASE_URL: 0.0.0.0
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - redis_database
      - mongo_database

  # propsycho_client:
  #   image: propsycho_client
  #   build:
  #     context: ./client
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 4173:4173
